### ISSUE TITLE
Proper config for Plex running on NAS?

### ISSUE THREAD

**Issue by fourg** [nomego/Lazyman.bundle#2]
Have Plex running on a Synology NAS which I've added this plug-in for and can access it, however I can only playback the short recaps, not the full replay or live games.  I tried adding "127.0.0.1 nlsk.neulion.com" minus the quotes to the /etc/hosts file of the NAS and rebooting it, but still same issue.  Am I missing a step possibly?

Edit: Resolved this by adding "104.251.218.27 mf.svc.nhl.com" to the /etc/hosts file instead.

**Comment by squirrellydw** [comment]
is that you IP address that you added?
