### ISSUE TITLE
KeyError: No preference named 'quality' found.

### ISSUE THREAD

**Issue by EpicWolverine** [nomego/Lazyman.bundle#20]
I'm getting the error `KeyError: No preference named 'quality' found.` when trying to open a game on the Windows 10 app. Plex Web just says `This channel is not responding.`. Seems to relate to #19 since reverting to 0722138cace690c107eb636c2218c8a23a9fac39 seems to fix it. Is there a preferences file that I need to create and fill in?

**Comment by nomego** [comment]
I merged that pr a little quickly, without testing it myself. Will revert shortly.

**Comment by nomego** [comment]
@unclenoriega Can you please re-submit the PR with the preferences setup present?

**Comment by unclenoriega** [comment]
Sorry about that, will resubmit
