### ISSUE TITLE
Error on recap playback

### ISSUE THREAD

**Issue by Thracky** [nomego/Lazyman.bundle#25]
When attempting to play recaps on the latest version running on PMS 1.9.4.4325 (and at least back to 1.9.2)   I notice the following error:

`2017-10-11 11:50:04,235 (7f6e8d7fa700) :  DEBUG (runtime:125) - Calling function 'RecapMetadata'
2017-10-11 11:50:04,236 (7f6e8d7fa700) :  CRITICAL (sandbox:303) - Exception when calling function 'RecapMetadata' (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-1bf240a65/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 294, in call_named_function
    result = f(*args, **kwargs)
TypeError: RecapMetadata() got an unexpected keyword argument 'includeBandwidths'
`
Quick solution for me which seemed to work (though I'll admit I have zero actual knowledge of the Plex API) was to add includeBandwidths to the RecapMetadata function signature as follows:

`def RecapMetadata(type, date, recapid, sport, includeBandwidths=None):`

**Comment by nomego** [comment]
Is this only happening for recaps?
NHL and/or MLB?

**Comment by Thracky** [comment]
Yes only recaps and can only confirm on NHL recaps. I have not tested on
MLB, but can give it a whirl when I have a chance.

**Comment by nomego** [comment]
Pr merged, reopen if still an issue.
