### ISSUE TITLE
iOS and tvOS custom profiles

### ISSUE THREAD

**Issue by joelifer** [nomego/Lazyman.bundle#28]
Not so much an issue of Lazyman but I cannot find an answer to this after extensive research. I followed the instructions about commenting out the lines to get the channel working on iOS and tvOS. It works great as expected and Lazyman now plays on iOS/tvOS.

Problem is I have other channels that now break due to this edit and won't play content. So my questions is, is there a way to tell Channel A to use the default iOS profile located at /plexmediaserver/Resources/Profiles and Channel B (Lazyman) to use the custom profile I have written at /Library/Application Support/Plex Media Server/Profiles

Thanks!

**Comment by evilsparc** [comment]
Based on this [fairly detailed write-up of streaming profiles](https://forums.plex.tv/discussion/73702/writing-profiles-for-dlna-devices/p1) it unfortunately doesn't seem possible. Even though a lot of detail is listed about how PMS chooses which profile to apply to a client, it doesn't specifically say it's not possible to do what you are asking, to me though it pretty heavily implies it.

I was going to suggest that you ask the same question over at the forum post listed above but it looks like you already have. I'd be curious to know if the client augmented profiles the guy below you mentioned has any relevance towards finding a solution.

**Comment by evilsparc** [comment]
I wanted to follow up on this real quick. It appears as though a recent update to iOS (11.x?) changes support for makes it possible to stream Lazyman to the platform without modifying transcode profiles. My feedback on this is _very_ preliminary, but I have seem some success with iOS clients that have simply disabled Direct Play. I have not heard back on any success/failure with AppleTV. Hope this helps!

**Comment by evilsparc** [comment]
@joelifer I don’t know if this is still causing you trouble but I recently had a chance to do some further testing and it looks like as long as the Plex client you are using supports disabling of Direct Play (usually found under Settings > Advanced > Allow Direct Play) there is no need to modify streaming profiles on your server. iOS and tvOS clients only recently added this toggle in the last month or so. 

I have submitted a PR to reflect this change in the readme. Hope this helps!

**Comment by joelifer** [comment]
@ghost really need to work on my notifications...almost 3 years later. Thank you!
