### ISSUE TITLE
lazyman unraid

### ISSUE THREAD

**Issue by maxcore** [nomego/Lazyman.bundle#31]
hi 
i have this bug 

Oct 30, 2017 18:38:44.484 [0x2b2750604700] VERBOSE - It took 0.0 sec to serialize a list with 1 elements.
Oct 30, 2017 18:38:44.485 [0x2b2748600700] DEBUG - Completed: [192.168.2.134:62243] 200 GET /status/sessions (13 live) TLS GZIP 2ms 3759 bytes (pipelined: 47)
Oct 30, 2017 18:38:44.486 [0x2b2748600700] DEBUG - Completed: [192.168.2.134:62330] 200 GET /status/sessions (13 live) TLS GZIP 3ms 3832 bytes (pipelined: 2)
Oct 30, 2017 18:38:45.973 [0x2b2757c01700] WARN - Warning: ex: boost::filesystem::last_write_time: No such file or directory: "/config/Library/Application Support/Plex Media Server/Plug-ins/Lazyman.bundle/Contents/Code/.___init__.py", couldn't check file: /config/Library/Application Support/Plex Media Server/Plug-ins/Lazyman.bundle/Contents/Code/.___init__.py
Oct 30, 2017 18:38:45.973 [0x2b2757c01700] WARN - Warning: ex: boost::filesystem::last_write_time: No such file or directory: "/config/Library/Application Support/Plex Media Server/Plug-ins/Lazyman.bundle/Contents/Code/._game.py", couldn't check file: /config/Library/Application Support/Plex Media Server/Plug-ins/Lazyman.bundle/Contents/Code/._game.py
Oct 30, 2017 18:38:46.478 [0x2b2748801700] VERBOSE - We didn't receive any data from 192.168.2.134:62301 in time, dropping connection.
Oct 30, 2017 18:38:46.479 [0x2b2748801700] VERBOSE - We didn't receive any data from 192.168.2.134:62300 in time, dropping connection.
Oct 30, 2017 18:38:47.973 [0x2b2757c01700] WARN - Warning: ex: boost::filesystem::last_write_time: No such file or directory: "/config/Library/Application Support/Plex Media Server/Plug-ins/Lazyman.bundle/Contents/Code/.___init__.py", couldn't check file: /config/Library/Application Support/Plex Media Server/Plug-ins/Lazyman.bundle/Contents/Code/.___init__.py
Oct 30, 2017 18:38:47.974 [0x2b2757c01700] WARN - Warning: ex: boost::filesystem::last_write_time: No such file or directory: "/config/Library/Application Support/Plex Media Server/Plug-ins/Lazyman.bundle/Contents/Code/._game.py", couldn't check file: /config/Library/Application Support/Plex Media Server/Plug-ins/Lazyman.bundle/Contents/Code/._game.py
Oct 30, 2017 18:38:49.453 [0x2b2748801700] VERBOSE - Auth: We found auth token (xxxxxxxxxxxxxxxxxxxx), enabling token-based authentication.
Oct 30, 2017 18:38:49.453 [0x2b2748801700] DEBUG - Auth: authenticated user 1 as Maxcore

**Comment by nomego** [comment]
Try reinstalling the channel please.

**Comment by maxcore** [comment]
@nomego work know ! but not on my apple tv , still in dev ?

**Comment by nomego** [comment]
Try the workaround for iOS/tvOS at the end of the readme
