### ISSUE TITLE
Can't get a ping from nhl.zipstream.net

### ISSUE THREAD

**Issue by apefist** [nomego/Lazyman.bundle#32]
When I try to do step one of the prereqs, I get a "could not find host" error.

I am typing "ping nhl.zipstreams.net" without the quotes into windows cmd

I get something from nhl.zipstreams.com however

**Comment by nomego** [comment]
This has changed and is now powersports.ml instead. Instructions will be updated shortly.

**Comment by apefist** [comment]
This worked, thank you very much
