### ISSUE TITLE
Not work on my Apple TV

### ISSUE THREAD

**Issue by maxcore** [nomego/Lazyman.bundle#33]
<img width="1011" alt="capture d ecran 2017-11-04 08 49 09" src="https://user-images.githubusercontent.com/4043787/32405505-24521212-c13d-11e7-990c-db160645f5bc.png">

 

this is my config
am with unraid and my profile was here: 
/usr/lib/plexmediaserver/Resources/Profiles

i start and always spin logo and nothing start

what wrong ...

**Comment by evilsparc** [comment]
It looks like you haven’t commented out the hls video profile from your config (line #17). This is also covered in the README under the workaround section, which I would recommend you take another look at. I’m not familiar with unraid but the directory you’re editing from looks like the install path and not the data directory, which can cause issues.

**Comment by evilsparc** [comment]
Comment out line 17. I would also recommend taking another look at the README workaround section, as it looks like your editing this file from the install and not the data directory (which can cause problems).

**Comment by maxcore** [comment]
you have right ! thx !
work know
