### ISSUE TITLE
Live streams will not play

### ISSUE THREAD

**Issue by jkurelek** [nomego/Lazyman.bundle#36]
My issue seems similar to this one (#34). I will select a live or archived stream for playback and it will not play. If the settings are to transcode the stream, then I get an network error (shaka1001?), while if its set for direct playback, it just stops without giving an error.

Here are my setup details
PMS Version 1.9.7.4460
latest Lazyman.bundle (pulled from GIT today)
Host OS: PMS runs in a container running on unRAID 6.3.5
Player: Tested with plex web player and android app. Same result

I've made sure the hosts file is updated correctly. The one in the container should be the one that matters, but I've tried adding the lines to unRAID hosts file as well with no success.

Here is a log file where I've tried to start streams either as transcode or direct playback.
[com.plexapp.plugins.lazyman.log.zip](https://github.com/nomego/Lazyman.bundle/files/1473092/com.plexapp.plugins.lazyman.log.zip)

Thanks, any help is much appreciated

**Comment by SlothCroissant** [comment]
+1.

Works fine with the Windows app using the same DNS server. Can provide logs if needed, just not currently home to grab em.

**Comment by bsthilaire** [comment]
Same problem for me. The problem seem to be since the new plex version 1.9.7.

Ref : https://www.reddit.com/r/LazyMan/comments/7brute/was_working_on_plex_until_a_few_weeks_ago/

**Comment by evilsparc** [comment]
I'm not able to duplicate the issue described. I spun up a 1.9.6.x instance (running on Ubuntu) and then updated to 1.9.7.x. Under both versions I was able to start streams successfully to an iPhone and the web app. I know this isn't a super helpful post to sorting out the issue, but I wanted to contribute a perspective that 1.9.6/.7 seem to be ok with the plugin.

**Comment by tfmm** [comment]
I've confirmed I can duplicate, had 1.9.4.x running, this worked fine, upgraded to 1.9.7.x, no dice.  Downgraded back to 1.9.4.x and now all is well.  I'm running Plex on CentOS 7 x64.

**Comment by maxcore** [comment]
Great news guys last uptate from plex server fix the bug !!

`Plex Media Server 1.10.0.4516 is now available to Plex Pass users in the Beta update channel
NEW:
(Web) Updated Plex Web to 3.27.1
(DVR) Added functionality to remove commercials from recorded content (#5633)
(Live) Added the ability to seek within an active recording, with client support (#7270)
(Transcoder) Support for hardware decoding of 10-bit HEVC (#7738)
FIXES:
(DVR) A server's first recording of LATM-packetized AAC could fail (#7875)
(DVR) An issue where poor-quality signal could cause recordings to "stick", reporting as 100% complete (#7606)
(DVR) New Episodes Tonight hub now correctly starts at 7pm local time (#7614)
(DVR) Recordings could hang if the tuner lost its signal lock (#7606)
(DVR) Some DVB subtitles weren't recorded (#7700)
(Extras) Fixed extras regression in previous release (#7821)
(Hubs) Speed up music and TV hubs.
(Metadata) Add support for absolute ordering in TV episode filenames (#7159)
(On Deck) Fix a fairly large slowdown introduced recently (#7824)
(Streaming Brain) Correct bitrate restricted playback of some channel content (#7452)
(Streaming Brain) Corrected playback when ABR is requested but server limits streams to 320kbps (#7706)
(Transcoder) Fixed soft subs not appearing in some cases (#7597)
(Transcoder) Hardware encoding had reduced quality on Windows with Intel GPUs in some cases (#7887)`

**Comment by jkurelek** [comment]
I can also confirm that upgrading to PMS 1.10.0.4516 solved the issues.

**Comment by nomego** [comment]
Solved through PMS update.
