### ISSUE TITLE
Xbox One S PLEX app channel will not play streams

### ISSUE THREAD

**Issue by qcoomer** [nomego/Lazyman.bundle#39]
It used to play the streams but now it no longer will work since the Xbox One Plex app was updated...
Any help?

**Comment by evilsparc** [comment]
Does the app have a toggle to disable direct play / direct stream? If so, I’d try turning that off as a quick first step. If that doesn’t work, probably posting some logs from the plugin when you’re attempting a stream could help.

**Comment by thomashw** [comment]
FYI - I've had direct play/stream disabled for a while and it's been working ever since.

**Comment by qcoomer** [comment]
When i get home from work, i will try to post a log (how do i find them?).
Also, does the app have the toggle? or do i have to do something like the iOS workaround?
thanks for the responses

**Comment by thomashw** [comment]
Yes, you should see both toggles in the app. The logs are stored in a Plex Media Server/Logs/PMS Plugin Logs.

**Comment by qcoomer** [comment]
Thank you, it works now. unsure if i should close...
