### ISSUE TITLE
Channel Not Responding

### ISSUE THREAD

**Issue by nova-techies** [nomego/Lazyman.bundle#4]
I have a feeling this has something to do with Lazyman switching to streamlink in the backend.

No live game or previous game are working right now.  Let me know if this is a know issue.

**Comment by dcm386** [comment]
As far as I know the plugin doesn't really use the streamlink/liverstreamer stuff from lazyman so it shouldn't be affected by that change. There is an issue with the current version of this plugin however, where it does not work for playoff games. I've submitted a pull request #5 which seems to fix it on my end of things. Live games and replays are working for me.

**Comment by dpeet** [comment]
Works for me as well.  Can't believe I'm just finding out about this now!  Thanks @nomego for the channel and @dcm386 for the fix!

**Comment by nova-techies** [comment]
Well that did it.  Amazing what fours lines can do.
