### ISSUE TITLE
Plex Plugin not working

### ISSUE THREAD

**Issue by redpunk18** [nomego/Lazyman.bundle#42]
I was not able to get the latest games for the Plex app.  I also noticed that the channel was not showing up.  I checked the logs and noticed that there was an indentation error for the game.py file.  I looked for any indents and replaced them with spaces and everything works well not. I just wanted to let someone know so they can make the change and get it committed.  Thanks!

**Comment by Cynicalsomething** [comment]
This pull request should fix the issue:
https://github.com/nomego/Lazyman.bundle/pull/43

**Comment by MaDTaZ** [comment]
Good work @Cynicalsomething 
You tabs where to many but looks like you already fix it.
Thank

**Comment by nomego** [comment]
This should be fixed.
