### ISSUE TITLE
Browser and iOS clients not working since IP change

### ISSUE THREAD

**Issue by JanuarysLittleJoke** [nomego/Lazyman.bundle#54]
Since the IP change, my iOS client and browsers (Chrome and Safari on Mac) have stopped working for both MLB and NHL, live and replay. I'm running the latest version of the bundle, I've updated the hosts file on my server, and have the correct edits in the iOS.xml file. The Plex Media Player on the Mac still works fine.

**Comment by JanuarysLittleJoke** [comment]
Update:

The problem appeared due to the latest Plex update (1.13.0.5003). A new version of ffmpeg was bundled with that release that doesn't always work correctly with Ubuntu 16.04 LTS. This [Reddit comment](https://www.reddit.com/r/LazyMan/comments/8iz5fh/live_mlb_on_plex_works_on_v11234973/dzeic55/?context=1) explains the problem in more detail.

Interestingly, all other transcoding that I've tried still works fine on Plex. It appears that the way the LazyMan plugin is calling the transcoder results in an illegal instruction for the older version of ffmpeg. This would seem to mean it's possible for the LazyMan plugin to be fixed.

**Comment by ymgenesis** [comment]
Agreed, my Plex works with my other mp4, etc. media in my library, it's just the LazyMan.bundle that's broken. Hopefully this will be looked at soon, as I'm considering not upgrading to 18.04 just yet.

**Comment by JanuarysLittleJoke** [comment]
The latest Plex Media Server version (1.13.2.5154) fixes this.
