### ISSUE TITLE
NHL JSON payload size larger than JSON.ObjectFromUrl max

### ISSUE THREAD

**Issue by csmith1210** [nomego/Lazyman.bundle#58]
The plugin has been showing "Plugin Stopped Responding" for some users for the NHL games. A user on reddit tracked it down to the JSON schedule payload being larger than the default max for JSON.ObjectFromUrl. Fix is to set the max size directly in line 74 of __init__.py:

```
Line 74
- schedule = JSON.ObjectFromURL(scheduleUrl)
+ schedule = JSON.ObjectFromURL(scheduleUrl, max_size=9000000)
```

See [here](https://www.reddit.com/r/LazyMan/comments/axewlz/plex_plugin_showing_plugin_stopped_responding/) for more details. The user tried to submit a pull request but GitHub thought he was spam.

**Comment by nomego** [comment]
Fixed by #59
