### ISSUE TITLE
NHL couldn't create the playback session

### ISSUE THREAD

**Issue by laitosko** [nomego/Lazyman.bundle#62]
Hi

Just saw an update last night, which unfortunately didn't solve my case.

Not sure when this started(maybe few weeks ago?), but having issues when trying to watch live/condensed games via iOS. Using iOS custom profile. Hosts modified. Plex says _couldn't create playback session_

And if watching via browser, recap and condensed provides only 184p quality?

Plex Version 1.15.1.710 (Debian 8.11)

404 responses from logs?

> **Debug** — [com.plexapp.plugins.lazyman] Sending command over HTTP (GET): /video/lazyman/:/function/RecapMetadata?function_args=XXX

> **Debug** — (Capabilties) Passing down capabilities of 'protocols=http-streaming-video;videoDecoders=h264{profile:high&resolution:2160&level:41};audioDecoders=aac' to plug-in.

> **Debug** — HTTP requesting GET http://127.0.0.1:45633/video/lazyman/:/function/RecapMetadata?function_args=XXX

> **Debug** — HTTP 404 response from GET http://127.0.0.1:45633/video/lazyman/:/function/RecapMetadata?function_args=XXX

> **Debug** — [com.plexapp.plugins.lazyman] HTTP reply status 404, with 0 bytes of content.

> **Error** — HTTP 404 downloading url http://127.0.0.1:32400/video/lazyman/:/function/RecapMetadata?function_args=XXX

> **Error** — TranscodeUniversalRequest: unable to get container: /video/lazyman/:/function/RecapMetadata?function_args=XXX

**Comment by csmith1210** [comment]
I myself actually get 403 status errors for older days because of the main m3u8 being expired on iOS and the web browser, which I have a fix for, but my question is how you're able to access older days without getting 403'd. 

Also the actual plugin logs would be helpful too. You can find them here:
`../Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.plugins.lazyman.log`

**Comment by laitosko** [comment]
Confirmed. This is the exact error I can see from logs. And actually you're right. I can only access previous ~48h streams.

```
2019-03-17 14:14:37,749 (7f857affd700) :  DEBUG (runtime:125) - Calling function 'RecapMetadata'
2019-03-17 14:14:37,749 (7f857affd700) :  CRITICAL (sandbox:303) - Exception when calling function 'RecapMetadata' (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-ece95b3a1/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 294, in call_named_function
    result = f(*args, **kwargs)
TypeError: RecapMetadata() got an unexpected keyword argument 'offset'
```

Could you check this from your end. What do you get when launching recap by default? URL states quite poor quality on my end.

```
2019-03-17 14:14:37,630 (7f857affd700) :  DEBUG (runtime:125) - Calling function 'PlayRecap'
2019-03-17 14:14:37,631 (7f857affd700) :  INFO (__init__:363) -  --> Final recap_url: http://md-akc.med.nhl.com/mp4/nhl/2019/03/16/3322f009-06bb-4188-8aba-c04ab44e6d99/1552766445738/asset_192k.mp4
```

**Comment by csmith1210** [comment]
Unfortunately just launching by default gives me the following result (better than yours). Plex still wants to try to convert the feed and not just the the original, but I can still force it if I want.
```
2019-03-20 18:27:01,782 (1472b8d27700) :  DEBUG (runtime:125) - Calling function 'PlayRecap'
2019-03-20 18:27:01,783 (1472b8d27700) :  INFO (__init__:367) -  --> Final recap_url: http://md-akc.med.nhl.com/mp4/nhl/2019/03/16/b01a341b-e657-4ee4-9f6d-3dd0191c72e5/1552769161560/asset_1800k.mp4
```

**Comment by laitosko** [comment]
FYI

If you change the quality to 720p60 and not use 'auto', recaps will not start automatically and only works by manually changing the quality via playback settings. And by selecting anything via playback settings, LM starts the 192k stream every time. 

Went back to 'auto' and now 544p works by default.

![image](https://user-images.githubusercontent.com/21026878/54817970-df84a000-4ca0-11e9-9e01-7aaa30d997b2.png)
