### ISSUE TITLE
AppleTV "Enhanced Player" breaks the iOS work around

### ISSUE THREAD

**Issue by fkick** [nomego/Lazyman.bundle#64]
If you enable the new Plex "enhanced player" feature on the AppleTV and iOS apps, it will break the iOS/tvOS work around of disabling direct play via a profile.

**Comment by csmith1210** [comment]
(Preface: I don't have Plex Plus and don't use the enhanced player)

I don't think there's a solution to this on the Plug-in side. From my understanding, the enhanced player is inherently direct play. There is a thread on the Plex forums [here](https://forums.plex.tv/t/enhanced-player-breaks-custom-tvos-xml-profile/386983) that you could also post that you're having the same issue. I don't know what Plex did with the latest update, but apparently it worked before so it could just be a bug.

**Comment by fkick** [comment]
Thanks csmith1210. That's actually my thread :)

I didn't think there would be much we could do on the plugin side, figured it would just be a good FYI for others. 

Disabling the "enhanced player" in settings will restore functionality.

Thanks
