### ISSUE TITLE
Plex iOS client showing no content for Lazyman 

### ISSUE THREAD

**Issue by fkick** [nomego/Lazyman.bundle#65]
Looks like Plex May have broke plugins in the latest public iOS release, 5.12.1 as all plugins show “no content”. Some users have reported that adding **kwargs to portions of their scripts have worked. See https://forums.plex.tv/t/ios-app-plugins-no-content/392357/8?

**Comment by csmith1210** [comment]
You should make sure you have the latest update downloaded to your Plex server. This was fixed with a commit in #63, and the app currently works for me.
