### ISSUE TITLE
Skipping to spot in previous game

### ISSUE THREAD

**Issue by fletchto99** [nomego/Lazyman.bundle#7]
It seems that when you skip ahead in a recorded game it causes the stream to crash. It loads for a split second and then just closes. Let me know if you need any more information/logs?

**Comment by nomego** [comment]
Yeah, I've noticed this too, not sure how to fix it.

**Comment by evilsparc** [comment]
I was just trying this in the web app and it seems to be working. If I'm not just getting lucky and it's possible from the web app always, I wonder if a workaround for now is to use it to seek to a location and then cast to whatever screen you actually want to watch on?

**Comment by fletchto99** [comment]
Seems this issue was fixed a while ago - might've just been something on my end. Anyhow closing.
